[guiltyDeployment]
BROKER_HOST = 127.0.0.1
BROKER_PORT = 5672
USER = guiltySpark
PASSWORD = test
VHOST = guiltyDeployment
EXCHANGE = deploymentExchange
QUEUE = deploymentQueue
ROUTING_KEY = deployment   
;EXCHANGE_TYPE = ????
AUTO_DELETE = true

[frontend-QA]
BROKER_HOST = 127.0.0.1
BROKER_PORT = 5672
USER = guiltySpark
PASSWORD = test
VHOST = guiltyDeployment
EXCHANGE = deploymentExchange
QUEUE = frontendQA
ROUTING_KEY = frontendQA   
;EXCHANGE_TYPE = ????
AUTO_DELETE = true

[frontend-Prod]
BROKER_HOST = 127.0.0.1
BROKER_PORT = 5672
USER = guiltySpark
PASSWORD = test
VHOST = guiltyDeployment
EXCHANGE = deploymentExchange
QUEUE = frontendProd
ROUTING_KEY = frontendProd  
;EXCHANGE_TYPE = ????
AUTO_DELETE = true

[database-QA]
BROKER_HOST = 127.0.0.1
BROKER_PORT = 5672
USER = guiltySpark
PASSWORD = test
VHOST = guiltyDeployment
EXCHANGE = deploymentExchange
QUEUE = databaseQA
ROUTING_KEY = databaseQA
;EXCHANGE_TYPE = ????
AUTO_DELETE = true

[database-Prod]
BROKER_HOST = 127.0.0.1
BROKER_PORT = 5672
USER = guiltySpark
PASSWORD = test
VHOST = guiltyDeployment
EXCHANGE = deploymentExchange
QUEUE = databaseProd
ROUTING_KEY = databaseProd   
;EXCHANGE_TYPE = ????
AUTO_DELETE = true

[DMZ-QA]
BROKER_HOST = 127.0.0.1
BROKER_PORT = 5672
USER = guiltySpark
PASSWORD = test
VHOST = guiltyDeployment
EXCHANGE = deploymentExchange
QUEUE = dmzQA
ROUTING_KEY = dmzQA   
;EXCHANGE_TYPE = ????
AUTO_DELETE = true

[DMZ-Prod]
BROKER_HOST = 127.0.0.1
BROKER_PORT = 5672
USER = guiltySpark
PASSWORD = test
VHOST = guiltyDeployment
EXCHANGE = deploymentExchange
QUEUE = dmzProd
ROUTING_KEY = dmzProd   
;EXCHANGE_TYPE = ????
AUTO_DELETE = true

[test]
BROKER_HOST = 127.0.0.1
BROKER_PORT = 5672
USER = guiltySpark
PASSWORD = test
VHOST = guiltyDeployment
EXCHANGE = deploymentExchange
QUEUE = test
ROUTING_KEY = test   
;EXCHANGE_TYPE = ????
AUTO_DELETE = true
