[guiltyDatabase]
BROKER_HOST = 10.89.15.104
BROKER_PORT = 5672
USER = guiltySpark
PASSWORD = PqT^kwzFin9L&?
VHOST = guiltySpark
EXCHANGE = mainExchange
QUEUE = databaseQueue
ROUTING_KEY = database
;EXCHANGE_TYPE = ????
AUTO_DELETE = true






