[testServer]
BROKER_HOST = 127.0.0.1
BROKER_PORT = 5672
USER = test
PASSWORD = test
VHOST = testHost
EXCHANGE = testExchange
QUEUE = testQueue
;EXCHANGE_TYPE = ????
AUTO_DELETE = true

[guiltyDatabase]
BROKER_HOST = 10.89.15.104
BROKER_PORT = 5672
USER = guiltySpark
PASSWORD = test
VHOST = guiltySpark
EXCHANGE = mainExchange
QUEUE = databaseQueue
ROUTING_KEY = database
;EXCHANGE_TYPE = ????
AUTO_DELETE = true

[testDMZ]
BROKER_HOST = 127.0.0.1
BROKER_PORT = 5672
USER = test
PASSWORD = test
VHOST = testHostDMZ
EXCHANGE = testExchangeDMZ
QUEUE = testQueueDMZ
;EXCHANGE_TYPE = ????
AUTO_DELETE = true

[guiltyDMZ]
BROKER_HOST = 10.89.15.157
BROKER_PORT = 5672
USER = test
PASSWORD = test
VHOST = testHostDMZ
EXCHANGE = testExchangeDMZ
QUEUE = testQueueDMZ
;EXCHANGE_TYPE = ????
AUTO_DELETE = true