[testServer]
BROKER_HOST = 127.0.0.1
BROKER_PORT = 5672
USER = test
PASSWORD = test
VHOST = testHost
EXCHANGE = testExchange
QUEUE = testQueue
;EXCHANGE_TYPE = ????
AUTO_DELETE = true

[guiltyDatabase]
BROKER_HOST = 10.89.15.104
BROKER_PORT = 5672
USER = guiltySpark
PASSWORD = test
VHOST = guiltySpark
EXCHANGE = mainExchange
QUEUE = databaseQueue
ROUTING_KEY = database
;EXCHANGE_TYPE = ????
AUTO_DELETE = true

[deploymentServer]
BROKER_HOST = 
BROKER_PORT = 5672
USER = guiltySpark
PASSWORD = test
VHOST = guiltySpark
EXCHANGE = mainExchange
QUEUE = deploymentQueue
ROUTING_KEY = deployment
;EXCHANGE_TYPE = ????
AUTO_DELETE = true
